### ISSUE TITLE
port to 1.12+?

### ISSUE THREAD

**Issue by 1231234md5** [SmallJiu/MultipleCompressedBlocks#3]
This is a good mod, but the thing I don't like about it is that it isn't supporting 1.12+. Can you port it to 1.12+? I'm wating for it!

**Comment by SmallJiu** [comment]
Maybe not, because this mod is my test mod, for after mods to do basis. And publishing it is just publishing the mod I casually wrote.

也许不会，因为这个mod是我的测试mod，给我之后的mod打基础，而发布出来只是把我随手写的mod发布出来而已.
